import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS } from '../constants/theme';

const { width, height } = Dimensions.get('window');
const PRIMARY_COLOR = COLORS.PRIMARY;
const SECONDARY_COLOR = COLORS.SECONDARY;
const BACKGROUND_COLOR = COLORS.BACKGROUND;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BACKGROUND_COLOR },
  splashContainer: { flex: 1, backgroundColor: PRIMARY_COLOR, justifyContent: 'center', alignItems: 'center' },
  splashLogoContainer: { width: 110, height: 110, backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 35, justifyContent: 'center', alignItems: 'center', marginBottom: 25, shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.15, shadowRadius: 10, elevation: 5 },
  splashTitle: { color: '#fff', fontSize: 28, fontWeight: 'bold', letterSpacing: 1 },
  splashSubTitle: { color: 'rgba(255,255,255,0.7)', fontSize: 14, marginTop: 8, fontWeight: '500' },
  welcomeTop: {
    flex: 0.6,
    backgroundColor: PRIMARY_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 40 : 0,
  },
  welcomeLogo: {
    width: 100,
    height: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  welcomeTitle: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  welcomeSubTitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 16,
    marginTop: 8,
  },
  welcomeBottom: {
    flex: 0.4,
    backgroundColor: '#fff',
    paddingHorizontal: 30,
    justifyContent: 'center',
  },
  btnOutlineWelcome: {
    height: 50,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: PRIMARY_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    flexDirection: 'row',
  },
  btnOutlineTextWelcome: {
    color: PRIMARY_COLOR,
    fontSize: 16,
    fontWeight: '600',
  },
  guestNoteWelcome: {
    color: '#aaa',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 15,
  },
  btnRed: { backgroundColor: PRIMARY_COLOR, height: 50, borderRadius: 12, justifyContent: 'center', alignItems: 'center', flexDirection: 'row' },
  btnRedText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  btnOutline: { height: 50, borderRadius: 12, borderWidth: 2, borderColor: PRIMARY_COLOR, justifyContent: 'center', alignItems: 'center', marginTop: 15, flexDirection: 'row' },
  btnOutlineText: { color: PRIMARY_COLOR, fontSize: 16, fontWeight: '600' },
  btnGray: { backgroundColor: '#f0f0f0', height: 50, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  btnGrayText: { color: '#555', fontSize: 16, fontWeight: '500' },
  guestNote: { color: '#bbb', fontSize: 12, textAlign: 'center', marginTop: 15 },
  topBar: { backgroundColor: PRIMARY_COLOR, padding: 20, paddingTop: 30 },
  topBarRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  topBarTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  topBarSub: { color: 'rgba(255,255,255,0.7)', fontSize: 12, marginTop: 2 },
  label: { fontSize: 14, color: '#999', marginTop: 20 },
  inputContainer: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#ddd', paddingVertical: 10 },
  input: { flex: 1, fontSize: 16, color: '#1a1a1a' },
  infoText: { fontSize: 12, color: '#bbb', marginTop: 10 },
  inputField: { backgroundColor: '#fafafa', borderWidth: 1, borderColor: '#eee', borderRadius: 10, padding: 12, marginTop: 8, fontSize: 14, color: '#111111' },
  genderRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  genderBtn: { flex: 1, borderWidth: 1, borderColor: '#eee', borderRadius: 10, padding: 10, alignItems: 'center' },
  genderBtnActive: { flex: 1, borderWidth: 2, borderColor: PRIMARY_COLOR, borderRadius: 10, padding: 10, alignItems: 'center' },
  genderText: { color: '#bbb', fontSize: 12 },
  genderTextActive: { color: PRIMARY_COLOR, fontSize: 12, fontWeight: 'bold' },
  shortcutGrid: { flexDirection: 'row', flexWrap: 'wrap', padding: 10 },
  shortcutItem: { width: (width - 40) / 2, backgroundColor: '#f8f8f8', padding: 20, margin: 5, borderRadius: 15, alignItems: 'center', borderWidth: 1, borderColor: '#eee' },
  shortcutText: { fontSize: 12, color: '#555', marginTop: 8 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', padding: 15, color: '#999' },
  card: { backgroundColor: '#f8f8f8', borderRadius: 15, padding: 15, borderWidth: 1, borderColor: '#eee' },
  cardTitle: { fontSize: 16, fontWeight: 'bold', color: '#1a1a1a' },
  cardSub: { fontSize: 12, color: '#999', marginTop: 5 },
  cardDesc: { fontSize: 12, color: '#555', marginTop: 10 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  cardFooter: { flexDirection: 'row', marginTop: 10, gap: 5 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, alignSelf: 'flex-start' },
  badgeText: { fontSize: 10, fontWeight: 'bold' },
  statsRow: { flexDirection: 'row', paddingHorizontal: 15, gap: 10, marginBottom: 20 },
  statBox: { flex: 1, padding: 15, borderRadius: 12, alignItems: 'center' },
  statValue: { fontSize: 24, fontWeight: 'bold' },
  statLabel: { fontSize: 10, marginTop: 2 },
  mapPlaceholder: { flex: 1, backgroundColor: '#e4ede4', position: 'relative' },
  customPin: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  pinArrow: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 5,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#fff',
    alignSelf: 'center',
    marginTop: -2
  },
  pin: { position: 'absolute', width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#fff' },
  mapLegend: { position: 'absolute', bottom: 20, alignSelf: 'center', backgroundColor: '#fff', paddingHorizontal: 15, paddingVertical: 10, borderRadius: 25, flexDirection: 'row', alignItems: 'center', elevation: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 4.65 },
  mapFilters: { flexDirection: 'row', padding: 15, gap: 10, backgroundColor: '#fff' },
  chip: { backgroundColor: '#ffeaea', paddingHorizontal: 15, paddingVertical: 10, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 5, elevation: 2 },
  chipText: { fontSize: 13, color: '#A32D2D', fontWeight: 'bold' },

  urgentAlert: { backgroundColor: '#ffeaea', padding: 15, borderRadius: 12, marginTop: 10 },
  urgentAlertTitle: { color: '#A32D2D', fontWeight: 'bold', fontSize: 14 },
  urgentAlertSub: { color: '#A32D2D', fontSize: 12, marginTop: 2 },
  timeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 },
  timeBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: '#eee' },
  timeBtnActive: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 2, borderColor: PRIMARY_COLOR },
  timeText: { color: '#bbb', fontSize: 12 },
  timeTextActive: { color: PRIMARY_COLOR, fontSize: 12, fontWeight: 'bold' },
  confirmContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  successCircle: { width: 80, height: 80, backgroundColor: '#eaf3de', borderRadius: 40, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  confirmTitle: { fontSize: 20, fontWeight: 'bold', color: '#1a1a1a' },
  confirmSub: { fontSize: 14, color: '#999', textAlign: 'center', marginTop: 10, lineHeight: 20 },
  settingItem: { flexDirection: 'row', alignItems: 'center', padding: 15, borderBottomWidth: 1, borderBottomColor: '#f8f8f8' },
  settingText: { flex: 1, fontSize: 14, marginLeft: 15 },
  chatAvatar: { width: 45, height: 45, borderRadius: 22.5, backgroundColor: 'rgba(255,255,255,0.2)', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  chatAvatarText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  chatTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  chatSubTitle: { color: 'rgba(255,255,255,0.8)', fontSize: 12, marginTop: 2 },
  messageBubble: { maxWidth: '80%', paddingHorizontal: 15, paddingVertical: 12, borderRadius: 10, marginBottom: 15 },
  messageHospital: { backgroundColor: '#f2f2f2', alignSelf: 'flex-start' },
  messageUser: { backgroundColor: PRIMARY_COLOR, alignSelf: 'flex-end' },
  messageTextHospital: { color: '#111', fontSize: 14, lineHeight: 20 },
  messageTextUser: { color: '#fff', fontSize: 14, lineHeight: 20 },
  chatInputContainer: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 25 : 55,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    backgroundColor: '#fff',
    alignItems: 'center'
  },
  chatInput: { flex: 1, borderWidth: 1, borderColor: '#eee', borderRadius: 8, paddingHorizontal: 15, paddingVertical: 10, fontSize: 14, backgroundColor: '#fafafa', marginRight: 10, color: '#111111' },
  chatSendBtn: { width: 45, height: 45, backgroundColor: PRIMARY_COLOR, borderRadius: 22.5, justifyContent: 'center', alignItems: 'center' },
  chatListItem: { flexDirection: 'row', padding: 15, borderBottomWidth: 1, borderBottomColor: '#f0f0f0', alignItems: 'center' },
  chatListAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: PRIMARY_COLOR, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  chatListAvatarText: { color: '#fff', fontWeight: 'bold', fontSize: 18 },
  chatListContent: { flex: 1 },
  chatListHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  chatListName: { fontSize: 16, fontWeight: 'bold', color: '#111' },
  chatListTime: { fontSize: 12, color: '#999' },
  chatListTimeUnread: { fontSize: 12, color: '#25D366', fontWeight: 'bold' },
  chatListMessage: { fontSize: 14, color: '#666', flex: 1, marginRight: 10 },
  unreadBadge: { backgroundColor: '#25D366', width: 20, height: 20, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  unreadBadgeText: { color: '#fff', fontSize: 10, fontWeight: 'bold' },
  fab: { position: 'absolute', bottom: 20, right: 20, width: 60, height: 60, borderRadius: 30, backgroundColor: PRIMARY_COLOR, justifyContent: 'center', alignItems: 'center', elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3 },
  statusDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: PRIMARY_COLOR,
  },
  miniStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 5,
  },
  listStatusDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: BACKGROUND_COLOR,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4CD964',
    marginRight: 2,
    shadowColor: '#4CD964',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 5,
  },
  tipCard: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 10,
    borderLeftWidth: 5,
    marginBottom: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  tipTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  tipDesc: {
    fontSize: 12,
    color: '#777',
    marginTop: 5,
  },
  resendText: {
    fontSize: 12,
    color: '#999',
    marginTop: 10,
    textAlign: 'center',
  },
  blueInfoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E6F0FA',
    padding: 10,
    borderRadius: 8,
    marginTop: 15,
  },
  blueInfoText: {
    color: '#0C447C',
    fontSize: 12,
    marginLeft: 6,
  },
});
